name: zhi_ming
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+7

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  sensors_plus: ^6.1.1
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  deepseek_api: ^0.1.2
  dio: ^5.4.1
  http: ^1.2.1
  intl: ^0.19.0
  flutter_markdown: ^0.7.7+1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^4.2.1
  adapty_flutter: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: font/NotoSansSC-Thin.woff2
          weight: 100
        - asset: font/NotoSansSC-ExtraLight.woff2
          weight: 200
        - asset: font/NotoSansSC-Light.woff2
          weight: 300
        - asset: font/NotoSansSC-Regular.woff2
          weight: 400
        - asset: font/NotoSansSC-Medium.woff2
          weight: 500
        - asset: font/NotoSansSC-SemiBold.woff2
          weight: 600
        - asset: font/NotoSansSC-Bold.woff2
          weight: 700
        - asset: font/NotoSansSC-ExtraBold.woff2
          weight: 800
        - asset: font/NotoSansSC-Black.woff2
          weight: 900

  assets:
    - assets/
    - assets/data/
    - assets/icons/
    - assets/heads.png
    - assets/tails.png
    - assets/shake.png
    - assets/data/hexagrams.json
